### ISSUE TITLE
Combatibility with Kanboard version 1.2.0?

### ISSUE THREAD

**Issue by timnis** [momo-aux/Duedate#1]
Hi,
Will this work with version 1.2.0? I don't see any mention of which version is supported.

-Timo

**Comment by momo-aux** [comment]
Did not check, just try and tell me result.
If it's not working I'll look into it.
Please add some descriptions of errors that you see.
The more detail you give, the faster I can fix it ;-)

**Comment by timnis** [comment]
I just tested.
When plugin was installed, toolbar was missing. First image plugin installed and second without it.
![image](https://user-images.githubusercontent.com/31338854/35808782-9d2b3d08-0a8f-11e8-9c15-b6db8b18af3b.png)

![image](https://user-images.githubusercontent.com/31338854/35808792-a3a21616-0a8f-11e8-8136-448fbeb23c8b.png)


My system is
    Application version: 1.2.0
    PHP version: 7.0.22-0ubuntu0.16.04.1
    PHP SAPI: fpm-fcgi
    OS version: Linux 4.4.0-112-generic
    Database driver: mysql
    Database version: 10.0.33-MariaDB-0ubuntu0.16.04.1
    Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0

I didn't noticed any errors on nginx logs or kanboard debug log.

**Comment by momo-aux** [comment]
Hi, I removed the toggle switch, now the menu should work in 1.2.0 also.
Please check and sorry for the long time for the update

**Comment by timnis** [comment]
Hi, many thanks now it works.
